server:
  port: 8081

spring.datasource:
  url: jdbc:h2:mem:catmash;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  hibernate.ddl-auto: none
  database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console:
  enabled: true
  path: /h2-console